/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as offchainResolverSol from "./OffchainResolver.sol";
export type { offchainResolverSol };
export type { IExtendedResolver } from "./IExtendedResolver";
