/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IResolverService } from "./IResolverService";
export type { OffchainResolver } from "./OffchainResolver";
