/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IResolverService__factory } from "./IResolverService__factory";
export { OffchainResolver__factory } from "./OffchainResolver__factory";
