/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as offchainResolverSol from "./OffchainResolver.sol";
export { IExtendedResolver__factory } from "./IExtendedResolver__factory";
