/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ENS__factory } from "./ENS__factory";
export { ENSRegistry__factory } from "./ENSRegistry__factory";
