name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node 20 and ubuntu-latest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      # running without protection here because for some reason it rejects to install dependencies even if the lockfile contains an optional dependency for a different platform
      # in our case it's fsevents. i tried many things with "--omit=optional" and overriding the dependency in package.json but it still fails
      # todo: figure out why
      - run: npm ci --force 

      - name: Lint
        run: npm run lint:check

      - name: Build
        run: npm run build

      - name: Test
        run: |
          npm i -g ganache
          npm run test --ci --coverage --maxWorkers=2 --testTimeout=30000
