name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node 20 and macos-latest

    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm ci

      # - name: Lint
      #   run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: |
          npm i -g ganache
          npm run test --ci --coverage --maxWorkers=2 --testTimeout=30000
